apiVersion: v1
kind: Service
metadata:
  name: traefik-internal
  labels:
    k8s-app: traefik-internal-ingress-lb
spec:
  selector:
    k8s-app: traefik-internal-ingress-lb
  ports:
    - port: 80
      name: http
      targetPort: 80
      nodePort: 30180
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-internal-console
  labels:
    k8s-app: traefik-internal-ingress-lb
spec:
  selector:
    k8s-app: traefik-internal-ingress-lb
  ports:
    - port: 80
      name: webui
      targetPort: 8080
      nodePort: 30188
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: traefik-internal-ingress-controller
  labels:
    k8s-app: traefik-internal-ingress-lb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        k8s-app: traefik-internal-ingress-lb
        name: traefik-internal-ingress-lb
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - image: traefik:v1.1.2
          name: traefik-internal-ingress-lb
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 8080
          args:
            - --web
            - --kubernetes
            - --kubernetes.endpoint=http://172.17.4.100:8080
            - --kubernetes.labelselector=ingress=internal