#cloud-config

coreos:
  update:
    reboot-strategy: "off"

  etcd2:
    name: etcd{{ etcdIndex }}
    initial-cluster: {{ initial_etcd_cluster }}
    initial-cluster-state: new
    
    advertise-client-urls: http://{{ ansible_env.COREOS_PRIVATE_IPV4 }}:2379
    initial-advertise-peer-urls: http://{{ ansible_env.COREOS_PRIVATE_IPV4 }}:2380
    
    listen-client-urls: http://0.0.0.0:2379
    listen-peer-urls: http://{{ ansible_env.COREOS_PRIVATE_IPV4 }}:2380

  flannel:
    interface: {{ ansible_env.COREOS_PRIVATE_IPV4 }}
    etcd_endpoints: http://127.0.0.1:2379

  units:

  - name: etcd2.service
    command: start
  - name: flanneld.service
    command: start
    drop-ins:
      - name: 50-network-config.conf
        content: |
          [Service]
          ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{"Network":"{{ pod_network }}", "Backend": {"Type": "{{ flannel_backend }}"}}'
  - name: docker.service
    command: start
    drop-ins:
      - name: 40-flannel.conf
        content: |
          [Unit]
          Requires=flanneld.service
          After=flanneld.service
