#cloud-config

coreos:

  flannel:
    interface: {{ ansible_env.COREOS_PRIVATE_IPV4 }}
    etcd_endpoints: http://{{ api_ip }}:2379

  units:

  - name: docker.service
    command: start
    drop-ins:
      - name: 40-flannel.conf
        content: |
          [Unit]
          Requires=flanneld.service
          After=flanneld.service